# Generated by Django 3.2.5 on 2021-08-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0003_alter_patientappointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointment_booking.appointment'),
        ),
    ]
